### PR TITLE
Added persistUrlParams config option

### PR DESCRIPTION
**Pull request by bancer**
```
/**
 * If `true` then URL parameters from the first step will be present in the URLs
 * of all other steps.
 *
 * @var bool
 */
	public $persistUrlParams = false;

### CODE REVIEW

**Comment by ProLoser** [comment]
This code seems a bit messy for what it essentially is adding.

For example:
```
unset($url['pass'], $url['named'], $url['paging'], $url['models'],
					$url['url'], $url['url'], $url['autoRender'], $url['bare'],
					$url['requested'], $url['return'], $url['isAjax'], $url['_Token']);
```

I'd say find an alternative way or simplify the logic. I honestly don't know if I agree with this needing to be a stateful setting however.

**Comment by bancer** [comment]
Well, that's the way it was implemented in [Router::reverse()](https://api.cakephp.org/2.8/source-class-Router.html#1089-1124). I'm not sure I understand what do you mean by "stateful setting". Anything that is stored in session may be considered stateful.

**Comment by bancer** [comment]
Could you be more specific on what you suggest?

**Comment by ProLoser** [comment]
Why aren't you calling that method

**Comment by bancer** [comment]
Because it returns the URL as a string. It is better to pass URL as an array to $this->controller->redirect() because there could be some functionality in AppController::redirect() that modifies the URL, f.ex. injects a language code.

**Pull request merged**
